spring:
  application:
    name: chat-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-chat:5432/chat_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:chat_service}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:chat-service}
    prefer-ip-address: false
