spring:
  application:
    name: project-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-project:5432/project_service_db
    username: project_service
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: project-service
    prefer-ip-address: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    use-root-path: false
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  use-management-port: false
  show-actuator: false

