spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://postgres-user:5432/user_service_db
    username: user_service
    password: password
  datasource:
    url: jdbc:postgresql://postgres-user:5432/user_service_db
    username: user_service
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    url: jdbc:postgresql://postgres-user:5432/user_service_db
    user: user_service
    password: password

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: user-service
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    use-root-path: false
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  use-management-port: false
  show-actuator: false

jwt:
  secrets:
    access: ${JWT_SECRETS_ACCESS}
    refresh: ${JWT_SECRETS_REFRESH}
  expirations:
    access: ${JWT_EXPIRATIONS_ACCESS:900000}
    refresh: ${JWT_EXPIRATIONS_REFRESH:1296000000}

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.data.r2dbc.core: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG
    liquibase: DEBUG
    org.liquibase: DEBUG
    ru.itmo.user_service: DEBUG